rules:
  - host: api.subees.beyond.com
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: subees-backend-service
              port:
                number: 8080

  - host: subees.beyond.com
    http:
      paths:
        - pathType: Prefix
          path: /
          backend:
            service:
              name: subees-frontend-service
              port:
                number: 80