apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: subees-ingress
  namespace: subees
spec:
  ingressClassName: nginx
  rules:
    - host: subees.beyond.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: subees-frontend
                port:
                  number: 80

    - host: api.subees.beyond.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: subees-backend
                port:
                  number: 8080